Exercise
Download employee retention dataset from here: https://www.kaggle.com/giripujar/hr-analytics.

Now do some exploratory data analysis to figure out which variables have direct and clear impact on employee retention (i.e. whether they leave the company or continue to work)
Plot bar charts showing impact of employee salaries on retention
Plot bar charts showing corelation between department and employee retention
Now build logistic regression model using variables that were narrowed down in step 1
Measure the accuracy of the model

In [2]:
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("HR_comma_sep.csv")
df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years Department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [4]:
plt.scatter(df.satisfaction_level,df.average_montly_hours,df.left,marker='+',color='red')

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test =train_test_split(df[['satisfaction_level']],df.left,test_size=0.1)

In [7]:
X_test

satisfaction_level
13452                0.62
14768                0.43
3946                 0.52
825                  0.11
5286                 0.64
...                   ...
12837                0.16
3135                 0.73
10901                0.66
2151                 0.79
13346                0.56

[1500 rows x 1 columns]

In [8]:
X_train

satisfaction_level
12075                0.11
4288                 0.53
9424                 0.93
10517                0.54
14735                0.75
...                   ...
176                  0.41
10622                0.60
12823                0.60
13302                0.86
8828                 0.93

[13499 rows x 1 columns]

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
model = LogisticRegression()

In [11]:
model.fit(X_train,y_train)

LogisticRegression()

In [12]:
model.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])

In [13]:
model.score(X_test,y_test)

0.7853333333333333

In [14]:
model.predict_proba(X_test)

array([[0.80116868, 0.19883132],
       [0.66143398, 0.33856602],
       [0.73352911, 0.26647089],
       ...,
       [0.8243381 , 0.1756619 ],
       [0.88506922, 0.11493078],
       [0.76224136, 0.23775864]])

In [15]:
import numpy as np

# 将标量转换为二维数组
input_data = np.array([0.442]).reshape(-1, 1)

# 调用 predict 方法
model.predict(input_data)

d:\anaconda3\envs\machineLearning\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])